openapi: 3.0.3
info:
  title: M-Team 用户登录 API
  description: M-Team 网站用户认证与登录相关 API 规格
  version: 1.0.0
  
servers:
  - url: https://api.m-team.cc
    description: M-Team API 服务器

paths:
  /api/login:
    post:
      summary: "the user authenticates with credentials"
      description: |
        - 用户通过用户名和密码进行身份验证
        - 如果用户启用了双因子认证（2FA），首次登录只验证用户名密码，需要后续提供OTP代码
        - 系统支持 Turnstile CAPTCHA 验证机制
        - 请求必须包含时间戳和签名以防止重放攻击
        - 成功登录后如果需要OTP，返回状态要求用户提供OTP代码
        - 完整登录成功后系统返回JWT令牌在Authorization头中
        - 系统返回新的设备标识(did)用于后续请求验证
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: 用户名
                  example: "gkw"
                password:
                  type: string
                  description: 用户密码
                  example: "123456"
                otpCode:
                  type: string
                  description: 双因子认证OTP代码（仅在启用2FA且首次验证通过后需要）
                  example: "654321"
                turnstile:
                  type: string
                  description: Turnstile CAPTCHA 验证令牌（可选）
                  example: ""
                _timestamp:
                  type: string
                  description: 请求时间戳（毫秒）
                  example: "1755096632310"
                _sgin:
                  type: string
                  description: 请求签名，用于防止重放攻击
                  example: "ueyVhDgIpmLtlBB6ge8vcRCVPZI="
              required:
                - username
                - password
                - _timestamp
                - _sgin
      parameters:
        - name: did
          in: header
          description: 设备唯一标识符
          required: true
          schema:
            type: string
            example: "2a348d9e588f49a1a1805657482093b9"
      responses:
        '200':
          description: 登录请求处理完成
          headers:
            Authorization:
              description: JWT认证令牌（仅在完全登录成功时返回）
              schema:
                type: string
                example: "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJna3ciLCJ1aWQiOjE3NTY0MywianRpIjoiMTQ2MDVmYTctNWQ3Ny00MTdlLThhYjgtYjA1MGMxNWRjYmY4IiwiaXNzIjoiaHR0cHM6Ly9hcGkubS10ZWFtLmNjIiwiaWF0IjoxNzU1MDk2NjM1LCJleHAiOjE3NTc2ODg2MzV9.Wg8c3FRVsdf2NzTAlwCft-_gMCKlXYPgYdRnCMsT5tkOkB47Wes5UPltHL9wt66bJpzo2EbRzZe8puIAqjyTyg"
            did:
              description: 新的设备标识符
              schema:
                type: string
                example: "fda40fccfa4f499aa3e2d38979b736df"
            Access-Control-Allow-Credentials:
              schema:
                type: string
                example: "true"
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: "https://kp.m-team.cc"
            Access-Control-Expose-Headers:
              schema:
                type: string
                example: "Authorization, did"
          content:
            application/json:
              schema:
                oneOf:
                  - type: object
                    description: 需要OTP验证的响应
                    properties:
                      message:
                        type: string
                        description: 提示信息
                      requireOtp:
                        type: boolean
                        description: 是否需要OTP验证
                        example: true
                      tempToken:
                        type: string
                        description: 临时令牌用于OTP验证
                  - type: object
                    description: 登录成功响应
                    properties:
                      success:
                        type: boolean
                        example: true
                      message:
                        type: string
                        example: "登录成功"
                      user:
                        type: object
                        properties:
                          uid:
                            type: integer
                            description: 用户唯一标识符
                            example: 175643
                          username:
                            type: string
                            description: 用户名
                            example: "gkw"
        '400':
          description: 请求参数错误
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: 错误信息
                  code:
                    type: string
                    description: 错误代码
        '401':
          description: 认证失败
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: 认证失败原因
                    examples:
                      - "用户名或密码错误"
                      - "OTP代码无效"
                      - "账户被锁定"
                  code:
                    type: string
                    description: 错误代码
        '429':
          description: 请求过于频繁
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "请求过于频繁，请稍后再试"
                  retryAfter:
                    type: integer
                    description: 重试等待时间（秒）

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT令牌认证
    DeviceId:
      type: apiKey
      in: header
      name: did
      description: 设备唯一标识符
      
  schemas:
    LoginRequest:
      type: object
      required:
        - username
        - password
        - _timestamp
        - _sgin
      properties:
        username:
          type: string
          description: 用户名
        password:
          type: string
          description: 用户密码
        otpCode:
          type: string
          description: 双因子认证OTP代码（可选）
        turnstile:
          type: string
          description: Turnstile CAPTCHA验证令牌（可选）
        _timestamp:
          type: string
          description: 请求时间戳（毫秒）
        _sgin:
          type: string
          description: 请求签名
    
    LoginResponse:
      oneOf:
        - $ref: '#/components/schemas/OtpRequiredResponse'
        - $ref: '#/components/schemas/LoginSuccessResponse'
    
    OtpRequiredResponse:
      type: object
      properties:
        message:
          type: string
          description: 提示信息
        requireOtp:
          type: boolean
          description: 是否需要OTP验证
        tempToken:
          type: string
          description: 临时令牌用于OTP验证
    
    LoginSuccessResponse:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
        user:
          type: object
          properties:
            uid:
              type: integer
              description: 用户唯一标识符
            username:
              type: string
              description: 用户名
    
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          description: 错误信息
        code:
          type: string
          description: 错误代码
